import type { User, Class, LessonNote, Assignment, Submission, Question, Activity } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Mr. Kwame Asante',
    email: 'teacher@classbridge.test',
    role: 'teacher',
    avatar: '',
  },
  {
    id: 'u2',
    name: 'Ama Serwaa',
    email: 'student@classbridge.test',
    role: 'student',
    avatar: '',
  },
  {
    id: 'u3',
    name: 'Mrs. Abena Owusu',
    email: 'headteacher@classbridge.test',
    role: 'headteacher',
    avatar: '',
  },
];

export const mockClasses: Class[] = [
  {
    id: 'c1',
    name: 'JHS 2 Integrated Science',
    subject: 'Integrated Science',
    level: 'JHS 2',
    term: 'Second Term',
    code: 'JHS2-SCI-4821',
    teacherId: 'u1',
    teacherName: 'Mr. Kwame Asante',
    students: ['u2'],
    createdAt: '2026-06-20T10:00:00Z',
  },
  {
    id: 'c2',
    name: 'JHS 1 Mathematics',
    subject: 'Mathematics',
    level: 'JHS 1',
    term: 'Second Term',
    code: 'JHS1-MATH-7392',
    teacherId: 'u1',
    teacherName: 'Mr. Kwame Asante',
    students: ['u2'],
    createdAt: '2026-06-22T14:30:00Z',
  },
];

export const mockLessons: LessonNote[] = [
  {
    id: 'l1',
    classId: 'c1',
    className: 'JHS 2 Integrated Science',
    teacherId: 'u1',
    teacherName: 'Mr. Kwame Asante',
    subject: 'Integrated Science',
    week: 4,
    date: '2026-06-25',
    topic: 'Photosynthesis',
    subTopic: 'The process by which plants make their own food',
    duration: 60,
    learningObjectives: 'Students will understand how plants produce food using sunlight, water, and carbon dioxide.',
    previousKnowledge: 'Students know that plants need sunlight and water to grow.',
    teachingMaterials: 'Textbook, chart showing photosynthesis process, potted plant, iodine solution.',
    introduction: 'Show students a potted plant and ask: "How do you think this plant gets its food?" Discuss responses for 5 minutes.',
    teacherActivities: 'Explain the photosynthesis equation. Demonstrate the starch test using iodine solution on a leaf. Guide students through the process step by step.',
    learnerActivities: 'Draw and label the photosynthesis process. Work in groups to discuss what happens when a plant is kept in the dark for 3 days. Present findings to class.',
    assessment: 'Draw a well-labeled diagram of photosynthesis. Write the word equation for photosynthesis. Explain why plants are called producers.',
    closure: 'Summarize key points. Assign homework: observe a plant at home and note changes when placed in different light conditions.',
    remarks: 'Students showed great interest in the starch test demonstration.',
    timeAllocations: [
      { id: 'ta1', activity: 'Introduction', minutes: 5 },
      { id: 'ta2', activity: 'Teacher Presentation', minutes: 20 },
      { id: 'ta3', activity: 'Group Activity', minutes: 20 },
      { id: 'ta4', activity: 'Assessment', minutes: 10 },
      { id: 'ta5', activity: 'Closure', minutes: 5 },
    ],
    status: 'approved',
    headteacherComment: 'Well-structured lesson with clear activities. Approved for teaching.',
    createdAt: '2026-06-23T08:00:00Z',
    updatedAt: '2026-06-24T10:30:00Z',
  },
  {
    id: 'l2',
    classId: 'c1',
    className: 'JHS 2 Integrated Science',
    teacherId: 'u1',
    teacherName: 'Mr. Kwame Asante',
    subject: 'Integrated Science',
    week: 5,
    date: '2026-06-27',
    topic: 'Respiration in Plants',
    subTopic: 'How plants breathe and release energy',
    duration: 60,
    learningObjectives: 'Students will describe the process of respiration in plants and differentiate it from photosynthesis.',
    previousKnowledge: 'Students understand photosynthesis and that plants need energy.',
    teachingMaterials: 'Textbook, germinating seeds in a flask, lime water, charts.',
    introduction: 'Review photosynthesis from previous lesson. Ask: "Do plants also need to release energy? How?"',
    teacherActivities: 'Explain aerobic respiration. Show experiment with germinating seeds and lime water. Compare photosynthesis and respiration using a chart.',
    learnerActivities: 'Observe the lime water experiment and record observations. Complete a comparison table of photosynthesis vs respiration.',
    assessment: 'Define respiration. Write the word equation for aerobic respiration. State two differences between photosynthesis and respiration.',
    closure: 'Recap the importance of respiration for plant survival. Preview next lesson on fermentation.',
    remarks: '',
    timeAllocations: [
      { id: 'ta6', activity: 'Introduction', minutes: 5 },
      { id: 'ta7', activity: 'Teacher Presentation', minutes: 25 },
      { id: 'ta8', activity: 'Experiment Observation', minutes: 15 },
      { id: 'ta9', activity: 'Assessment', minutes: 10 },
      { id: 'ta10', activity: 'Closure', minutes: 5 },
    ],
    status: 'submitted',
    createdAt: '2026-06-26T09:00:00Z',
    updatedAt: '2026-06-26T09:00:00Z',
  },
  {
    id: 'l3',
    classId: 'c2',
    className: 'JHS 1 Mathematics',
    teacherId: 'u1',
    teacherName: 'Mr. Kwame Asante',
    subject: 'Mathematics',
    week: 3,
    date: '2026-06-26',
    topic: 'Fractions',
    subTopic: 'Addition and subtraction of fractions',
    duration: 60,
    learningObjectives: 'Students will be able to add and subtract fractions with different denominators.',
    previousKnowledge: 'Students can identify proper and improper fractions.',
    teachingMaterials: 'Fraction charts, cardboard cutouts, worksheets.',
    introduction: 'Use a pizza analogy to introduce adding fractions. Ask students about sharing food.',
    teacherActivities: 'Demonstrate finding the LCM of denominators. Work through examples on the board. Guide students through practice problems.',
    learnerActivities: 'Use fraction cutouts to visualize addition. Solve problems on worksheets in pairs.',
    assessment: 'Solve: 1/2 + 1/3, 3/4 - 1/6, 2/5 + 3/10. Word problem: A cake was cut into 8 pieces. If John ate 3/8 and Mary ate 2/8, what fraction remains?',
    closure: 'Review steps for adding/subtracting fractions. Assign practice exercises.',
    remarks: '',
    timeAllocations: [
      { id: 'ta11', activity: 'Introduction', minutes: 5 },
      { id: 'ta12', activity: 'Teacher Presentation', minutes: 20 },
      { id: 'ta13', activity: 'Practice Problems', minutes: 20 },
      { id: 'ta14', activity: 'Assessment', minutes: 10 },
      { id: 'ta15', activity: 'Closure', minutes: 5 },
    ],
    status: 'draft',
    createdAt: '2026-06-26T11:00:00Z',
    updatedAt: '2026-06-26T11:00:00Z',
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: 'a1',
    classId: 'c1',
    className: 'JHS 2 Integrated Science',
    teacherId: 'u1',
    teacherName: 'Mr. Kwame Asante',
    title: 'Photosynthesis Diagram',
    description: 'Draw a well-labeled diagram showing the process of photosynthesis. Include: sunlight, chlorophyll, water, carbon dioxide, glucose, and oxygen. Write a short explanation of each stage.',
    totalMarks: 20,
    dueDate: '2026-06-30',
    createdAt: '2026-06-25T10:00:00Z',
  },
  {
    id: 'a2',
    classId: 'c1',
    className: 'JHS 2 Integrated Science',
    teacherId: 'u1',
    teacherName: 'Mr. Kwame Asante',
    title: 'Respiration Experiment Report',
    description: 'Write a report on the respiration experiment demonstrated in class. Include: aim, materials, procedure, observations, and conclusion.',
    totalMarks: 15,
    dueDate: '2026-07-03',
    createdAt: '2026-06-27T08:00:00Z',
  },
];

export const mockSubmissions: Submission[] = [
  {
    id: 's1',
    assignmentId: 'a1',
    assignmentTitle: 'Photosynthesis Diagram',
    studentId: 'u2',
    studentName: 'Ama Serwaa',
    classId: 'c1',
    answer: 'I have drawn a diagram showing a plant with leaves. The diagram shows arrows pointing from the sun to the leaf labeled "sunlight energy." There is an arrow from the roots to the leaf labeled "water (H2O)." An arrow from the air going into the leaf labeled "carbon dioxide (CO2)." Arrows coming out of the leaf show "oxygen (O2)" and "glucose (C6H12O6)." The chlorophyll is shown as green dots in the leaf. Explanation: During photosynthesis, plants use sunlight energy, water from the soil, and carbon dioxide from the air to make glucose (food) and release oxygen. This happens in the green parts of the plant where chlorophyll is present.',
    score: 18,
    feedback: 'Excellent work, Ama! Your diagram is well-labeled and your explanation is clear and accurate. You correctly identified all the raw materials and products of photosynthesis. To improve further, you could mention that this process occurs in the chloroplasts. Keep up the great work! Score: 18/20',
    status: 'graded',
    submittedAt: '2026-06-26T15:30:00Z',
  },
  {
    id: 's2',
    assignmentId: 'a2',
    assignmentTitle: 'Respiration Experiment Report',
    studentId: 'u2',
    studentName: 'Ama Serwaa',
    classId: 'c1',
    answer: '',
    status: 'pending',
    submittedAt: '',
  },
];

export const mockQuestions: Question[] = [
  {
    id: 'q1',
    lessonId: 'l1',
    lessonTopic: 'Photosynthesis',
    studentId: 'u2',
    studentName: 'Ama Serwaa',
    question: 'Sir, I am confused about when photosynthesis happens. Does it happen at night too? And if plants need sunlight, how do they survive at night?',
    replies: [
      {
        id: 'r1',
        userId: 'u1',
        userName: 'Mr. Kwame Asante',
        userRole: 'teacher',
        message: 'Great question, Ama! Photosynthesis only happens during the day when there is sunlight. At night, plants do NOT perform photosynthesis. However, they have a stored food (glucose) that they made during the day. They use this stored food at night through respiration to get energy. Think of it like cooking food during the day and eating it at night!',
        createdAt: '2026-06-24T09:15:00Z',
      },
    ],
    createdAt: '2026-06-23T16:00:00Z',
  },
  {
    id: 'q2',
    lessonId: 'l1',
    lessonTopic: 'Photosynthesis',
    studentId: 'u2',
    studentName: 'Ama Serwaa',
    question: 'Sir, can you explain again why the iodine solution turns blue-black when we test a leaf for starch? I did not understand that part.',
    replies: [],
    createdAt: '2026-06-26T10:30:00Z',
  },
];

export const mockActivities: Activity[] = [
  {
    id: 'act1',
    userId: 'u1',
    userName: 'Mr. Kwame Asante',
    userRole: 'teacher',
    action: 'created class',
    target: 'JHS 2 Integrated Science',
    timestamp: '2026-06-20T10:00:00Z',
  },
  {
    id: 'act2',
    userId: 'u1',
    userName: 'Mr. Kwame Asante',
    userRole: 'teacher',
    action: 'created lesson note',
    target: 'Photosynthesis - Week 4',
    timestamp: '2026-06-23T08:00:00Z',
  },
  {
    id: 'act3',
    userId: 'u3',
    userName: 'Mrs. Abena Owusu',
    userRole: 'headteacher',
    action: 'approved lesson note',
    target: 'Photosynthesis - Week 4',
    timestamp: '2026-06-24T10:30:00Z',
  },
  {
    id: 'act4',
    userId: 'u1',
    userName: 'Mr. Kwame Asante',
    userRole: 'teacher',
    action: 'created assignment',
    target: 'Photosynthesis Diagram',
    timestamp: '2026-06-25T10:00:00Z',
  },
  {
    id: 'act5',
    userId: 'u2',
    userName: 'Ama Serwaa',
    userRole: 'student',
    action: 'submitted assignment',
    target: 'Photosynthesis Diagram',
    timestamp: '2026-06-26T15:30:00Z',
  },
  {
    id: 'act6',
    userId: 'u1',
    userName: 'Mr. Kwame Asante',
    userRole: 'teacher',
    action: 'graded submission',
    target: 'Ama Serwaa - Photosynthesis Diagram (18/20)',
    timestamp: '2026-06-26T16:00:00Z',
  },
  {
    id: 'act7',
    userId: 'u1',
    userName: 'Mr. Kwame Asante',
    userRole: 'teacher',
    action: 'submitted lesson note for review',
    target: 'Respiration in Plants - Week 5',
    timestamp: '2026-06-26T09:00:00Z',
  },
  {
    id: 'act8',
    userId: 'u2',
    userName: 'Ama Serwaa',
    userRole: 'student',
    action: 'joined class',
    target: 'JHS 2 Integrated Science',
    timestamp: '2026-06-22T11:00:00Z',
  },
];
